# dotnet-aspnet/docker-compose.yml

services:
  dotnet-aspnet:
    build:
      context: .
    container_name: howdy-dotnet-aspnet
    ports:
      - "5010:8080"
    # volumes:
    #   - .:/app
    environment:
      - ASPNETCORE_URLS=http://+:8080
